# Claude Agent SDK Configuration for Synthetic Data Generator
# This configuration file defines settings for the agent mode

agent:
  # System prompt for the agent
  system_prompt: |
    You are an AI assistant specialized in synthetic data generation.

    Your role is to help users generate high-quality synthetic datasets by:
    1. Understanding their data requirements through natural conversation
    2. Detecting and resolving ambiguities in specifications
    3. Analyzing sample data patterns when provided
    4. Generating realistic synthetic data
    5. Exporting data in various formats

    Always be helpful, precise, and thorough in assisting with data generation tasks.

  # Allowed standard tools (Read, Write, Bash, etc.)
  allowed_tools:
    - Read
    - Write
    - Bash
    - Glob
    - Grep

  # Custom tools (automatically registered via MCP servers SDK)
  custom_tools:
    - analyze_requirements
    - detect_ambiguities
    - analyze_pattern
    - generate_data
    - export_data
    - list_formats
    - select_reasoning_strategy
    - list_reasoning_methods
    - deep_analyze_pattern
    - generate_with_modes
    - validate_quality
    - list_generation_modes

  # Claude Skills
  skills:
    # Built-in Anthropic Skills
    built_in:
      - xlsx  # Excel spreadsheet operations
      - pdf   # PDF document operations
      - docx  # Word document operations
      - pptx  # PowerPoint presentation operations

    # Custom Skills
    custom:
      - data-validation      # Advanced data quality validation
      - statistical-analysis # Deep statistical pattern recognition
      - data-visualization   # Charts, graphs, and visual reports
      - schema-inference     # Automatic schema and type detection
      - privacy-checker      # PII detection and privacy compliance
      - relational-mapper    # Multi-table relationship handling

  # Working directory for file operations
  working_directory: "./output"

  # Hooks configuration
  hooks:
    enable_pre_query: true
    enable_post_query: true
    enable_pre_tool: true
    enable_post_tool: true
    enable_on_error: true

# Tool-specific settings
tools:
  analyze_requirements:
    confidence_threshold: 0.7
    max_fields: 50

  detect_ambiguities:
    default_confidence_threshold: 0.7
    max_questions: 5

  generate_data:
    default_rows: 100
    max_rows: 10000
    enable_seed: true

  export_data:
    default_format: csv
    allowed_formats:
      - csv
      - json
      - excel
      - parquet
      - xml
      - sql
      - avro

# Generation settings
generation:
  quality_level: high
  null_percentage: 0.05
  duplicate_percentage: 0.02
  enable_constraints: true
  enable_pattern_matching: true

# Output settings
output:
  default_directory: "./output"
  create_subdirectories: true
  timestamp_files: true
  include_metadata: true

# Logging settings
logging:
  level: INFO
  enable_tool_logging: true
  enable_metrics: true

# Skills configuration
skills:
  # Data Validation Skill
  data_validation:
    enabled: true
    strict_mode: false
    fail_on_warning: false
    max_violations_to_report: 100
    quality_threshold: 0.85
    check_data_leakage: true
    check_pii_exposure: true

  # Statistical Analysis Skill
  statistical_analysis:
    enabled: true
    distribution_tests:
      - normal
      - exponential
      - uniform
      - poisson
      - gamma
      - beta
    significance_level: 0.05
    correlation_threshold: 0.7
    outlier_method: "isolation_forest"
    max_sample_size: 100000
    enable_time_series: true
    enable_multivariate: true

  # Data Visualization Skill
  data_visualization:
    enabled: true
    default_format: "html"
    dpi: 300
    figure_size: [12, 8]
    style: "seaborn"
    theme: "default"
    interactive: true
    save_static_copies: true
    output_directory: "output/visualizations"

  # Schema Inference Skill
  schema_inference:
    enabled: true
    confidence_threshold: 0.8
    sample_size: 1000
    enable_semantic_detection: true
    enable_constraint_inference: true
    enable_relationship_detection: true

  # Privacy Checker Skill
  privacy_checker:
    enabled: true
    pii_detection:
      enabled: true
      confidence_threshold: 0.8
      check_field_names: true
      check_field_values: true
    anonymization:
      default_method: "pseudonymization"
      preserve_distributions: true
    privacy_metrics:
      k_anonymity_threshold: 5
      l_diversity_threshold: 3
      t_closeness_threshold: 0.2
    compliance:
      check_gdpr: true
      check_hipaa: false
      check_ccpa: false

  # Relational Mapper Skill
  relational_mapper:
    enabled: true
    relationship_detection:
      enabled: true
      confidence_threshold: 0.8
      check_naming_patterns: true
      check_value_overlap: true
    generation:
      maintain_referential_integrity: true
      use_transactions: true
      batch_size: 1000
    cardinality:
      one_to_many_avg: 3
      many_to_many_avg: 5
    export:
      include_foreign_keys: true
      include_indexes: true
      include_constraints: true
